#!/usr/bin/env node
// Regenerates the two committed, machine-derived source modules from the REAL
// epubcheck jar's CLI output, so an epubcheck upgrade regenerates them instead
// of anyone hand-editing:
//
//   src/help-text.ts        <- `java -jar epubcheck.jar --help`
//   src/list-checks-data.ts <- `java -jar epubcheck.jar --listChecks`
//
//   npm run generate:cli-data
//
// The jar is located by scripts/epubcheck-jar.ts (env/glob, never hardcoded),
// and Java comes from the mise-provisioned toolchain (this script runs under
// `mise exec`, so `java` is on PATH; override with the JAVA env var).
//
// help-text.ts is emitted with the version header interpolated from the
// library's EPUBCHECK_VERSION (a template literal), so it carries NO hardcoded
// version token. As a guard, the jar's self-reported version must match
// EPUBCHECK_VERSION or this script refuses to write.

import { spawnSync } from "node:child_process";
import { writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { EPUBCHECK_VERSION } from "epubcheck-standalone";
import { JAVA, resolveJarPath } from "./epubcheck-jar.ts";

const here = dirname(fileURLToPath(import.meta.url));
const srcDir = join(here, "..", "src");
const jar = resolveJarPath();

function runJar(...args: string[]): string {
  const r = spawnSync(JAVA, ["-jar", jar, ...args], {
    encoding: "utf8",
    maxBuffer: 1 << 28,
  });
  if (r.error) {
    throw new Error(`failed to run \`${JAVA} -jar ${jar} ${args.join(" ")}\`: ${r.error.message}`);
  }
  if (r.status !== 0) {
    throw new Error(
      `\`${JAVA} -jar ${jar} ${args.join(" ")}\` exited ${r.status}\n${r.stderr}`,
    );
  }
  return r.stdout;
}

/** Escape a string so it is safe inside a single-line backtick template. */
function escapeTemplate(s: string): string {
  return s
    .replace(/\\/g, "\\\\")
    .replace(/`/g, "\\`")
    .replace(/\$\{/g, "\\${")
    .replace(/\r/g, "\\r")
    .replace(/\n/g, "\\n")
    .replace(/\t/g, "\\t");
}

function buildHelpModule(rawHelp: string): string {
  const m = rawHelp.match(/^EPUBCheck v(\S+)/);
  if (!m) {
    throw new Error(`could not find the "EPUBCheck v<version>" header in --help output`);
  }
  const jarVersion = m[1];
  if (jarVersion !== EPUBCHECK_VERSION) {
    throw new Error(
      `jar reports epubcheck v${jarVersion} but the library's EPUBCHECK_VERSION is ` +
        `${EPUBCHECK_VERSION}; rebuild the engine/library for this jar before regenerating.`,
    );
  }
  const header = `EPUBCheck v${jarVersion}`;
  const rest = rawHelp.slice(header.length);
  return (
    "// AUTO-GENERATED by scripts/generate-cli-data.ts from the official epubcheck\n" +
    "// CLI `--help` output. Do not edit by hand; re-run `npm run generate:cli-data`\n" +
    "// after an epubcheck upgrade.\n" +
    "//\n" +
    "// HELP_OUTPUT is the VERBATIM text `epubcheck --help` / `-h` prints to stdout\n" +
    "// (source: com/adobe/epubcheck/util/messages.properties key `help_text`, plus\n" +
    "// the trailing newline outWriter.println adds), kept as exact bytes so the CLI\n" +
    "// is byte-identical to the real tool. The ONLY substitution is the version in\n" +
    "// the header line, interpolated from the library's EPUBCHECK_VERSION so an\n" +
    "// epubcheck upgrade regenerates it with no hand-edit here.\n" +
    'import { EPUBCHECK_VERSION } from "epubcheck-standalone";\n' +
    "\n" +
    "export const HELP_OUTPUT = `EPUBCheck v${EPUBCHECK_VERSION}" +
    escapeTemplate(rest) +
    "`;\n"
  );
}

function buildListChecksModule(rawList: string): string {
  return (
    "// AUTO-GENERATED by scripts/generate-cli-data.ts from the official epubcheck\n" +
    "// CLI `--listChecks` output. Do not edit by hand; re-run\n" +
    "// `npm run generate:cli-data` after an epubcheck upgrade.\n" +
    "//\n" +
    "// LIST_CHECKS_TSV is the VERBATIM message dictionary `epubcheck --listChecks`\n" +
    "// prints (default/English locale): a tab-separated table of every message id,\n" +
    "// its default severity, message template, and suggestion (source:\n" +
    "// com.adobe.epubcheck.tool.MessageDictionaryDumper over the default\n" +
    "// MessageBundle). It is static per epubcheck version, embedded here to\n" +
    "// reproduce --listChecks byte-for-byte without the JVM.\n" +
    "export const LIST_CHECKS_TSV = " +
    JSON.stringify(rawList) +
    ";\n"
  );
}

// The non-English locales whose message bundles epubcheck ships. `--listChecks
// --locale <tag>` localizes the Message/Suggestion columns from the localized
// MessageBundle (MessageDictionaryDumper reads the report's localized
// dictionary); the ID/Severity columns are locale-invariant. These are exactly
// the shipped-locale KEYS the CLI's resolveLocale() can return (English is the
// default LIST_CHECKS_TSV, so it is not repeated here). A region-qualified tag
// (fr-FR, de-DE, ...) resolves to its bare-language dump, so only the canonical
// keys are dumped.
const LISTCHECKS_LOCALES = [
  "da", "de", "es", "fr", "it", "ja", "ko-KR", "nl", "pt-BR", "zh-TW",
] as const;

function buildLocaleListChecksModule(byLocale: Record<string, string>): string {
  const entries = Object.keys(byLocale)
    .map((k) => `  ${JSON.stringify(k)}: ${JSON.stringify(byLocale[k])},`)
    .join("\n");
  return (
    "// AUTO-GENERATED by scripts/generate-cli-data.ts from the official epubcheck\n" +
    "// CLI `--listChecks --locale <tag>` output. Do not edit by hand; re-run\n" +
    "// `npm run generate:cli-data` after an epubcheck upgrade.\n" +
    "//\n" +
    "// LIST_CHECKS_TSV_BY_LOCALE maps each shipped NON-English locale key (the keys\n" +
    "// resolveLocale() can return) to the VERBATIM message dictionary\n" +
    "// `epubcheck --listChecks --locale <tag>` prints in that locale: the same\n" +
    "// ID/Severity columns as English with the Message/Suggestion columns localized\n" +
    "// (source: com.adobe.epubcheck.tool.MessageDictionaryDumper over the localized\n" +
    "// MessageBundle). English is the default LIST_CHECKS_TSV in list-checks-data.ts.\n" +
    "export const LIST_CHECKS_TSV_BY_LOCALE: Record<string, string> = {\n" +
    entries +
    "\n};\n"
  );
}

console.log(`Using jar: ${jar}`);
console.log(`Using java: ${JAVA}`);

const helpModule = buildHelpModule(runJar("--help"));
const listModule = buildListChecksModule(runJar("--listChecks"));
const byLocale: Record<string, string> = {};
for (const loc of LISTCHECKS_LOCALES) {
  byLocale[loc] = runJar("--listChecks", "--locale", loc);
}
const localeListModule = buildLocaleListChecksModule(byLocale);

writeFileSync(join(srcDir, "help-text.ts"), helpModule);
writeFileSync(join(srcDir, "list-checks-data.ts"), listModule);
writeFileSync(join(srcDir, "list-checks-locale-data.ts"), localeListModule);

console.log(
  "Wrote src/help-text.ts, src/list-checks-data.ts, and src/list-checks-locale-data.ts",
);
